bitcoin:
  uri: https://test.tes3t

zuul:
  routes:
    payment-gateway:
      path: /payment-gateway/**
      service-id: payment-gateway
    literary-society:
      path: /literary-society/**
      service-id: literary-society
    bank:
      path: /bank/**
      service-id: bank
    bank2:
      path: /bank2/**
      service-id: bank2
    pcc:
      path: /pcc/**
      service-id: pcc
    paypal:
      path: /paypal/**
      service-id: paypal
    bitcoin:
      path: /bitcoin/**
      service-id: bitcoin
    qr:
      path: /qr/**
      service-id: qr
